In [1]:
library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)
library(rtracklayer)
library(GenomicRanges)

ChIPseeker v1.38.0

If you use ChIPseeker in published research, please cite:
Qianwen Wang, Ming Li, Tianzhi Wu, Li Zhan, Lin Li, Meijun Chen, Wenqin Xie, Zijing Xie, Erqiang Hu, Shuangbin Xu, Guangchuang Yu. Exploring epigenomic datasets by ChIPseeker. Current Protocols 2022, 2(10): e585

Loading required package: GenomicFeatures

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Warning message:
“package ‘S4Vectors’ was built under R version 4.3.3”
Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Warning message:
“package ‘IRanges’ was built under R version 4.3.3”
Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Warning message:
“package ‘GenomicRanges’ was built under R version 4.3.3”
Loading required package: AnnotationDbi

Loading required package: Biobase

Warning message:
“package ‘Biobase’ was built under R version 4.3.3”
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.




Warning message:
“package ‘rtracklayer’ was built under R version 4.3.3”

In [ ]:
# pc_hic_data = read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/ActivePromoterEnhancerLinks.tsv",sep='\t',header = T)

In [ ]:
# peak_bed = data.frame(seqnames=pc_hic_data[,1],start=pc_hic_data[,2],end=pc_hic_data[,3],strand="*")

# peak_bed = peak_bed[!duplicated(peak_bed),]
# peaks <- makeGRangesFromDataFrame(peak_bed, keep.extra.columns = TRUE)
# txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
# peak_annotation <- annotatePeak(peaks, TxDb = txdb, tssRegion = c(-2000, 2000), 
#                                 annoDb = "org.Hs.eg.db")

>> preparing features information...		 2025-03-11 06:45:44 PM
>> identifying nearest features...		 2025-03-11 06:45:44 PM
>> calculating distance from peak to TSS...	 2025-03-11 06:45:44 PM
>> assigning genomic annotation...		 2025-03-11 06:45:44 PM
>> adding gene annotation...			 2025-03-11 06:45:47 PM

'select()' returned 1:many mapping between keys and columns

>> assigning chromosome lengths			 2025-03-11 06:45:47 PM
>> done...					 2025-03-11 06:45:47 PM

In [ ]:
# head(as.data.frame(peak_annotation))

  seqnames start   end     width strand annotation       geneChr geneStart
1 chr1     1206873 1212438  5566 *      Promoter (<=1kb) 1       1189292
2 chr1     1239425 1278099 38675 *      Promoter (<=1kb) 1       1227764
3 chr1     1309968 1313315  3348 *      Promoter (<=1kb) 1       1309110
4 chr1     1505406 1516638 11233 *      Promoter (<=1kb) 1       1477053
5 chr1     1545982 1552729  6748 *      Promoter (<=1kb) 1       1550795
6 chr1     1648710 1672992 24283 *      Promoter (<=1kb) 1       1634170
  geneEnd geneLength geneStrand geneId transcriptId distanceToTSS
1 1209234 19943      2          118424 uc001ado.3   0
2 1241309 13546      2          116983 uc001aea.2   0
3 1310246  1137      2          54998  uc001afb.1   0
4 1510262 33210      2          29101  uc001agd.3   0
5 1554590  3796      1          142678 uc021oet.1   0
6 1655791 21622      2          728642 uc009vkr.3   0
  ENSEMBL         SYMBOL
1 ENSG00000160087 UBE2J2
2 ENSG00000131584 ACAP3
3 ENSG00000175756 AURKAIP1
4 ENSG00000160075 SSU72
5 ENSG00000197530 MIB2
6 ENSG00000008128 CDK11A
  GENENAME
1 ubiquitin conjugating enzyme E2 J2
2 ArfGAP with coiled-coil, ankyrin repeat and PH domains 3
3 aurora kinase A interacting protein 1
4 SSU72 homolog, RNA polymerase II CTD phosphatase
5 MIB E3 ubiquitin protein ligase 2
6 cyclin dependent kinase 11A

In [ ]:
# write.table(x=as.data.frame(peak_annotation),file = "/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/promoter_annotation.txt",sep = "\t",col.names = T,row.names = F,quote = F)

In [ ]:
# pc_hic_data$prom = paste(pc_hic_data[,1],pc_hic_data[,2],pc_hic_data[,3],sep="-")
# peak_annot = as.data.frame(peak_annotation)
# peak_annot$prom = paste(peak_annot[,1],peak_annot[,2],peak_annot[,3],sep="-")
# peak_annot2 = merge(pc_hic_data,peak_annot,by='prom')

In [25]:
peak_annot_out = peak_annot2[,c(2:10,17,25,27)]
# head(peak_annot_out)
write.table(peak_annot_out,file = "/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_with_gene.txt",sep = "\t",col.names = T,row.names = F,quote = F)

In [ ]:
# pc_hic_data$hg19_cre = paste(pc_hic_data[,5],pc_hic_data[,6],pc_hic_data[,7],sep="-")

In [ ]:
# # 输出peak信息，做Liftover.
# cre_hg19 = pc_hic_data[,c(5,6,7)]
# cre_hg19 = cre_hg19[!duplicated(cre_hg19),]
# cre_hg19$index = c(1:nrow(cre_hg19))
# write.table(cre_hg19,file = "/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_hg19.bed",sep='\t',row.names = F,col.names = F,quote = F)

In [38]:
max(cre_hg19$index)

[1] 25232

In [41]:
# system("/home/shaliu_fu/software/kentUtils/bin/linux.x86_64/liftOver /home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_hg19.bed /home/shaliu_fu/multireg/benchmark/db/hg19ToHg38.over.chain.gz /home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_hg38.bed /home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_unmap.bed",intern=TRUE)

In [ ]:
# cre_hg38 = read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_hg38.bed",sep='\t')
# # head(cre_hg38)
# colnames(cre_hg19) <- c("chr",'start','end','index')
# colnames(cre_hg38) <- c("chr", 'start', 'end', 'index')
# cre_lift = merge(cre_hg38,cre_hg19, by='index')

In [ ]:
# cre_lift$hg38_coord = paste(cre_lift[,2],cre_lift[,3],cre_lift[,4],sep = "-")
# cre_lift$hg19_coord = paste(cre_lift[,5],cre_lift[,6],cre_lift[,7],sep = "-")

In [ ]:
# system("zcat /home/shaliu_fu/multireg/benchmark/bench_dataset/10X_PBMC/PBMC-multiome-raw-ATAC-peaks.mtx/features.tsv.gz | cut -f 1 | awk '{gsub("-", "\t"); print}' | intersectBed -a stdin -b /home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/hic_peaks_hg38.bed -wa -wb -f 0.6 > /home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/pbmc_peaks_with_hic.txt")

In [ ]:
# pbmc_with_hic = read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/pbmc_peaks_with_hic.txt",sep='\t')

In [ ]:
# colnames(pbmc_with_hic)[7] = 'index'
# pbmc_with_hic_merge<-merge(pbmc_with_hic,cre_hg19,by="index")

In [ ]:
# pbmc_with_hic_merge$peaks = paste(pbmc_with_hic_merge[,2],pbmc_with_hic_merge[,3],pbmc_with_hic_merge[,4],sep = "-")
# pbmc_with_hic_merge$hg19_cre = paste(pbmc_with_hic_merge[,8],pbmc_with_hic_merge[,9],pbmc_with_hic_merge[,10],sep = "-")

In [ ]:
# head(pbmc_with_hic_merge)

  index V1   V2      V3      V4   V5      V6      chr  start   end
1 1     chr1 1008905 1009827 chr1 1008296 1021819 chr1  943676  957199
2 1     chr1 1012996 1013917 chr1 1008296 1021819 chr1  943676  957199
3 1     chr1 1019166 1019999 chr1 1008296 1021819 chr1  943676  957199
4 2     chr1 1098927 1099916 chr1 1098888 1104828 chr1 1034268 1040208
5 2     chr1 1103897 1104771 chr1 1098888 1104828 chr1 1034268 1040208
6 3     chr1 1106598 1107360 chr1 1104828 1107763 chr1 1040208 1043143
  peaks                hg19_coord           hg19_cre
1 chr1-1008905-1009827 chr1-943676-957199   chr1-943676-957199
2 chr1-1012996-1013917 chr1-943676-957199   chr1-943676-957199
3 chr1-1019166-1019999 chr1-943676-957199   chr1-943676-957199
4 chr1-1098927-1099916 chr1-1034268-1040208 chr1-1034268-1040208
5 chr1-1103897-1104771 chr1-1034268-1040208 chr1-1034268-1040208
6 chr1-1106598-1107360 chr1-1040208-1043143 chr1-1040208-1043143

In [ ]:
# peak_annot_out$hg19_cre = paste(peak_annot_out[,5],peak_annot_out[,6],peak_annot_out[,7],sep="-")

# peaks_to_gene <- merge(pbmc_with_hic_merge, peak_annot_out)
# colnames(peaks_to_gene)

 [1] "hg19_cre"      "index"         "V1"            "V2"
 [5] "V3"            "V4"            "V5"            "V6"
 [9] "chr"           "start"         "end"           "peaks"
[13] "hg19_coord"    "baitChr"       "baitSt"        "baitEnd"
[17] "baitID"        "oeChr"         "oeSt"          "oeEnd"
[21] "oeID"          "cellType.s."   "annotation"    "distanceToTSS"
[25] "SYMBOL"

In [ ]:
# peaks_to_gene2 = peaks_to_gene[,c(3:5,12,22:25)]

In [ ]:
# write.table(peaks_to_gene2,file = "/home/shaliu_fu/multireg/benchmark/datasets/pbmc/pc_HiC/pbmc_peak_to_gene_gold.txt",sep = "\t",row.names = F,col.names = T,quote = F)

In [2]:
# tfknockdb data process
library(data.table)
tf_knockdb_result = fread("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/knockTFDB/knocktf_v2_main_human.txt",sep = "\t")

Warning message:
“package ‘data.table’ was built under R version 4.3.3”

In [30]:
sel_dataset = read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/knockTFDB/select_dataset_metadata.txt",sep = "\t",header = T)
dim(sel_dataset)

[1] 17  8

In [10]:
head(tf_knockdb_result)

  Sample_ID     TF   Gene    Mean_Case  Mean_Control FC       Log2FC  Rank
1 DataSet_01_01 ESR1 KRT4    2753.89913 90.77417     30.33795 4.92305 1
2 DataSet_01_01 ESR1 UPK1A   1551.08281 174.91983     8.86741 3.14851 2
3 DataSet_01_01 ESR1 GABBR2  576.56122  67.74582      8.51065 3.08927 3
4 DataSet_01_01 ESR1 GPNMB   3130.93968 369.18497     8.48062 3.08417 4
5 DataSet_01_01 ESR1 PSCA    435.51542  62.68898      6.94726 2.79644 5
6 DataSet_01_01 ESR1 GPR109B 866.33428  128.77601     6.72745 2.75006 6
  P_value     Corrected_P up_down NCBI_Official_Symbol Entrez_ID
1 1.8795e-09  7.04142e-06 1       KRT4                  3851
2 1.87194e-09 7.04142e-06 1       UPK1A                11045
3 4.51591e-08 2.68134e-05 1       GABBR2                9568
4 3.42503e-09 7.04142e-06 1       GPNMB                10457
5 4.46111e-09 7.04142e-06 1       PSCA                  8000
6 3.90576e-09 7.04142e-06 1       HCAR3                 8843
  Ensembl_ID      TE_TF promoter_TF SE_TF TE_TF_name promoter_TF_name
1 ENSG00000170477 404   30          468   ESR1       AP2GAMMA
2 ENSG00000105668 441   49          364   ESR1       AML1
3 ENSG00000136928 637   78          568   ESR1       AHR
4 ENSG00000136235 484   17          498   ESR1       ARID3A
5 ENSG00000167653 445   49          434   ESR1       ASCL1
6 ENSG00000255398 380    0          352   AHR        NA
  SE_TF_name
1 ESR1
2 ESR1
3 ESR1
4 ESR1
5 ESR1
6 AHRARNT

In [32]:
tf_knockdb_sel<-subset(tf_knockdb_result,Sample_ID %in% sel_dataset[,1])
length(unique(tf_knockdb_sel$Sample_ID))

[1] 15

In [44]:
# 对于knockdb计算的样本，先评估敲除效果，剔除敲除效果较差的分组。
target_eff = subset(tf_knockdb_sel,TF==Gene)
sel_tf = subset(target_eff,abs(Log2FC)>1)$TF

In [46]:
tf_knockdb_sel2 = subset(tf_knockdb_sel,TF %in% sel_tf & P_value<0.05)

In [ ]:
table(tf_knockdb_sel2$Sample_ID)
# 多的用rank，少的可以忽略。

DataSet_01_162 DataSet_01_164 DataSet_01_165 DataSet_01_166 DataSet_01_168
          5038           4103           3030           3615            362
 DataSet_01_73 DataSet_03_229 DataSet_03_230 DataSet_03_231
          2612            624              3            279

In [60]:
head(tf_knockdb_sel2[,c(1,2,3,7,8,9)])

  Sample_ID     TF     Gene    Log2FC   Rank P_value
1 DataSet_01_73 ZNF148 TBC1D12  1.35962 19   0.00027
2 DataSet_01_73 ZNF148 HLTF    -1.22217 28   0.00035
3 DataSet_01_73 ZNF148 MGAT4A   1.13880 42   0.00245
4 DataSet_01_73 ZNF148 WASF1   -1.13860 43   0.00021
5 DataSet_01_73 ZNF148 CAPRIN2 -1.12676 45   0.00171
6 DataSet_01_73 ZNF148 PAQR3   -1.08201 52   0.00017

In [100]:
out_tab = tf_knockdb_sel2[,c(1,2,3,7,8,9)]
write.table(out_tab,file = "/home/shaliu_fu/multireg/benchmark/datasets/pbmc/knockTFDB/sel_tf_gene_part1.txt",row.names = F,col.names = T,sep = "\t",quote = F )

      Sample_ID      TF     Gene      Log2FC      Rank P_value
1     DataSet_01_73  ZNF148 TBC1D12    1.35962     19  0.00027
2     DataSet_01_73  ZNF148 HLTF      -1.22217     28  0.00035
3     DataSet_01_73  ZNF148 MGAT4A     1.13880     42  0.00245
4     DataSet_01_73  ZNF148 WASF1     -1.13860     43  0.00021
5     DataSet_01_73  ZNF148 CAPRIN2   -1.12676     45  0.00171
6     DataSet_01_73  ZNF148 PAQR3     -1.08201     52  0.00017
7     DataSet_01_73  ZNF148 NFE2L3     1.07100     54  0.00012
8     DataSet_01_73  ZNF148 RSAD1     -1.05303     57  0.00039
9     DataSet_01_73  ZNF148 ARMC8     -0.99448     64  0.00012
10    DataSet_01_73  ZNF148 LMO7       0.98609     65  0.00027
11    DataSet_01_73  ZNF148 SAP30L    -0.98349     66  0.00109
12    DataSet_01_73  ZNF148 GPR137B    0.93711     77  0.00484
13    DataSet_01_73  ZNF148 CD74       0.90679     86  0.00012
14    DataSet_01_73  ZNF148 MMRN2     -0.90268     89  0.00012
15    DataSet_01_73  ZNF148 PKP4      -0.89747     90  0.00013
16    DataSet_01_73  ZNF148 PTCD3     -0.89161     95  0.00063
17    DataSet_01_73  ZNF148 SEMA4C     0.88014     97  0.00039
18    DataSet_01_73  ZNF148 LYZ        0.87501     98  0.00016
19    DataSet_01_73  ZNF148 QPCTL     -0.87392     99  0.01699
20    DataSet_01_73  ZNF148 TLE1       0.87061    100  0.00011
21    DataSet_01_73  ZNF148 PBLD      -0.86690    102  0.00458
22    DataSet_01_73  ZNF148 DNAJC10   -0.85740    106  0.00051
23    DataSet_01_73  ZNF148 HSPA2      0.84460    111  0.00049
24    DataSet_01_73  ZNF148 ID1       -0.83825    115  0.00012
25    DataSet_01_73  ZNF148 ZNF667    -0.83706    116  0.0247
26    DataSet_01_73  ZNF148 CKAP4      0.83673    117  0.00026
27    DataSet_01_73  ZNF148 F2R        0.83484    118  0.00214
28    DataSet_01_73  ZNF148 HLA-DPB1   0.82721    121  0.00039
29    DataSet_01_73  ZNF148 BACH2      0.82178    123  0.00018
30    DataSet_01_73  ZNF148 DNAJC24   -0.82087    124  0.00079
⋮     ⋮              ⋮      ⋮         ⋮           ⋮    ⋮
19637 DataSet_03_231 SATB1  KCNC4     -0.06289078 2959 0.0446771124808884
19638 DataSet_03_231 SATB1  HOXA5     -0.06231440 2983 0.0249155222738301
19639 DataSet_03_231 SATB1  PSG2       0.06206429 2992 0.0484598703275996
19640 DataSet_03_231 SATB1  PLA2G5     0.06178720 3005 0.0191091265487069
19641 DataSet_03_231 SATB1  RNF32     -0.06143007 3017 0.0492043732295559
19642 DataSet_03_231 SATB1  AKAP12    -0.06142499 3018 0.0303274158675046
19643 DataSet_03_231 SATB1  NEUROG3   -0.06141046 3019 0.0467597977559424
19644 DataSet_03_231 SATB1  NTN4      -0.06124298 3029 0.0349488334968745
19645 DataSet_03_231 SATB1  FOXN1      0.06054636 3061 0.0388030704320507
19646 DataSet_03_231 SATB1  CHRFAM7A   0.05994923 3086 0.0289337942751497
19647 DataSet_03_231 SATB1  TRIM67     0.05984943 3094 0.0323044448888341
19648 DataSet_03_231 SATB1  PTPRB      0.05963130 3101 0.0334461794215273
19649 DataSet_03_231 SATB1  LRRC18     0.05915786 3120 0.0208074373750295
19650 DataSet_03_231 SATB1  TNKS2      0.05863785 3142 0.0408540979369369
19651 DataSet_03_231 SATB1  OR6C1     -0.05796004 3173 0.0231220234713507
19652 DataSet_03_231 SATB1  KLC3      -0.05738796 3205 0.0323380167970337
19653 DataSet_03_231 SATB1  GRID1      0.05713514 3214 0.0489222771822019
19654 DataSet_03_231 SATB1  LMO2       0.05686486 3228 0.0338948910253129
19655 DataSet_03_231 SATB1  ZNF547    -0.05680811 3229 0.0365034547470479
19656 DataSet_03_231 SATB1  PAGE4     -0.05633865 3249 0.0242577608988536
19657 DataSet_03_231 SATB1  HOXC6     -0.05605385 3267 0.0223183758313545
19658 DataSet_03_231 SATB1  REM1      -0.05599058 3269 0.037520064119605
19659 DataSet_03_231 SATB1  DAB2IP     0.05286903 3453 0.0398731824263862
19660 DataSet_03_231 SATB1  KIF18A    -0.05236574 3482 0.0418620865115707
19661 DataSet_03_231 SATB1  KRTAP13-2  0.05004362 3617 0.0369860405489537
19662 DataSet_03_231 SATB1  FLRT3     -0.04975976 3632 0.0490256407337294
19663 DataSet_03_231 SATB1  HOXD11     0.04770903 3760 0.0369639000465019
19664 DataSet_03_231 SATB1  TTN       -0.04554995 3913 0.0269323966570666
19665 DataSet_03_231 SATB1  PCDH7     -0.04219349 4154 0.0366312932656466
19666 DataSet_03_231 SATB1  RASA4     -0.03836919 4454 0.0303056316611954

In [62]:
library(GEOquery)

Loading required package: Biobase

Warning message:
“package ‘Biobase’ was built under R version 4.3.3”
Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Setting options('download.file.method.GEOquery'='auto')

Setting options('GEOquery.inmemory.gpl'=FALSE)

In [67]:
setdiff(unique(sel_dataset[,1]),unique(tf_knockdb_result$Sample_ID))

[1] "DataSet_03_363" "DataSet_03_427"

In [70]:
# 读入'DataSet_03_363''DataSet_03_427' 表达矩阵，寻找样本分组信息。
subset(sel_dataset,Dataset.ID %in% c('DataSet_03_363','DataSet_03_427'))

   Dataset.ID     TF    Molecular.Type Knock.Method Biosample.Type
9  DataSet_03_363 MYC   TF             siRNA        Primary cell
16 DataSet_03_427 FOXP3 TF             siRNA        Primary cell
   Tissue.Type      Biosample.Name PBMCs.cell.type
9  Peripheral_blood T lymphocyte
16 Peripheral_blood Naive Treg

In [78]:
myc_tab <- read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/knockTFDB/DataSet_03_363.txt",row.names = 1,header = T,sep = "\t")
foxp3_tab<-read.table("/home/shaliu_fu/multireg/benchmark/datasets/pbmc/knockTFDB/DataSet_03_427.txt",row.names = 1,header = T,sep = "\t")

In [79]:
gsm_ids =colnames(myc_tab)
gsm_metadata <- list()
group = c()
# 循环查询每个 GSM 编号的元数据
for (gsm in gsm_ids) {
    # 获取 GSM 信息
    gsm_data <- getGEO(gsm)
    # gsm_metadata[[gsm]] <- Meta(gsm_data)
    meta <- Meta(gsm_data)   # 提取元数据
    group = c(group,meta$title)
}

Using locally cached version of GSM3612026 found here:
/tmp/RtmpuKqJbY/GSM3612026.soft

Using locally cached version of GSM3612027 found here:
/tmp/RtmpuKqJbY/GSM3612027.soft

Using locally cached version of GSM3612028 found here:
/tmp/RtmpuKqJbY/GSM3612028.soft

Using locally cached version of GSM3612029 found here:
/tmp/RtmpuKqJbY/GSM3612029.soft

Using locally cached version of GSM3612030 found here:
/tmp/RtmpuKqJbY/GSM3612030.soft

Using locally cached version of GSM3612031 found here:
/tmp/RtmpuKqJbY/GSM3612031.soft

In [80]:
gsm_ids =colnames(foxp3_tab)
gsm_metadata <- list()
group2 = c()
# 循环查询每个 GSM 编号的元数据
for (gsm in gsm_ids) {
    # 获取 GSM 信息
    gsm_data <- getGEO(gsm)
    # gsm_metadata[[gsm]] <- Meta(gsm_data)
    meta <- Meta(gsm_data)   # 提取元数据
    group2 = c(group2,meta$title)
}

In [81]:
print(group)

[1] "Jurkat-control-si-1" "Jurkat-control-si-2" "Jurkat-control-si-3"
[4] "Jurkat-c-Myc-si-1"   "Jurkat-c-Myc-si-2"   "Jurkat-c-Myc-si-3"

In [82]:
print(group2)

 [1] "nTreg_FOXP3-HDR-KO_donor5" "nTreg_Cas9_donor5"
 [3] "Tconv_donor5"              "nTreg_FOXP3-HDR-KO_donor3"
 [5] "nTreg_Cas9_donor3"         "Tconv_donor3"
 [7] "nTreg_FOXP3-HDR-KO_donor4" "nTreg_Cas9_donor4"
 [9] "Tconv_donor4"              "nTreg_FOXP3-HDR-KO_donor7"
[11] "nTreg_Cas9_donor7"         "Tconv_donor7"

In [98]:
# 按分组计算差异基因，fc, pvalue
get_pvalue <-function(mydata){
    return(wilcox.test(x=as.numeric(mydata[1:3]),
        y = as.numeric(mydata[4:6]),paired = T)$p.value)
}

myc_diff_tab<- data.frame(row.names = rownames(myc_tab),fc = rowMeans(myc_tab[,4:6]+0.01)/rowMeans(myc_tab[,1:3]+0.01),pvalue = apply(as.matrix(myc_tab),1,get_pvalue))

Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :
“cannot compute exact p-value with zeroes”
Warning message in wilcox.test.default(x = as.numeric(mydata[1:3]), y = as.numeric(mydata[4:6]), :

In [ ]:
get_pvalue <-function(mydata){
    return(c(wilcox.test(x=as.numeric(mydata[c(3,6,9,12)]),
        y = as.numeric(mydata[c(1,4,7,10)],paired=T))$p.value,
        wilcox.test(x=as.numeric(mydata[c(3,6,9,12)]),
        y = as.numeric(mydata[c(2,5,8,11)],paired=T))$p.value
        ))
}

foxp3_diff<- data.frame(row.names = rownames(foxp3_tab),
fc1 = rowMeans(foxp3_tab[,c(1,4,7,10)]+0.01)/rowMeans(foxp3_tab[,c(3,6,9,12)]+0.01),
fc2=rowMeans(foxp3_tab[,c(2,5,8,11)]+0.01)/rowMeans(foxp3_tab[,c(3,6,9,12)]+0.01))

foxp3_ptab<-data.frame(apply(as.matrix(foxp3_tab),1,get_pvalue))

Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(1, :
“cannot compute exact p-value with ties”
Warning message in wilcox.test.default(x = as.numeric(mydata[c(3, 6, 9, 12)]), y = as.numeric(mydata[c(2, :
“cannot compute exact p-value with ties”

ERROR: Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 19381, 2

In [117]:
# dim(foxp3_ptab)
# dim(foxp3_diff)
foxp3_diff_tab<-cbind(foxp3_diff,t(foxp3_ptab))

In [118]:
foxp3_diff_tab

             fc1         fc2         1          2
WASH7P        0.88983511  0.9166931  0.02857143 0.48571429
LOC729737     0.79778055  0.8505472  0.20000000 0.68571429
LOC100133331  0.82570876  0.8207814  0.02857143 0.48571429
LOC100288069  0.91285422  0.8898626  0.19126699 0.88454944
FAM87B        0.72413508  0.7854853  0.75681818 0.86866106
LINC00115     0.74376330  0.8363800  0.02857143 0.10375368
LINC01128     0.96441913  0.9902086  0.68571429 1.00000000
FAM41C        1.00000000 40.6240625         NaN 0.45325470
SAMD11       26.00000000  1.0000000  0.45325470        NaN
NOC2L         1.05167881  1.0027693  0.34285714 0.88571429
KLHL17        0.89396836  0.9027229  0.02857143 0.20000000
PLEKHN1       0.83950321  1.0448394  0.34285714 0.68571429
PERM1         0.03846154  1.0000000  0.45325470 1.00000000
HES4          8.89838377  6.4811920  0.02283622 0.16347531
ISG15         1.11820829  1.1057390  0.02857143 0.02857143
AGRN          1.11647018  0.9950888  0.19126699 1.00000000
C1orf159      1.01355623  0.9600043  0.88571429 0.68571429
TTLL10        0.82314561  1.0865583  1.00000000 0.87859344
TNFRSF18      1.06778037  1.1302577  0.68571429 0.34285714
TNFRSF4       1.26407592  1.1955279  0.02857143 0.20000000
SDF4          1.01756121  0.9942852  0.20000000 1.00000000
B3GALT6       1.00434158  0.9953111  0.88571429 0.88571429
FAM132A       0.97000711  0.6676326  0.88385257 0.38363033
UBE2J2        1.00681800  0.9826334  0.34285714 1.00000000
SCNN1D        0.84916531  0.7371174  0.02857143 0.68571429
ACAP3         0.94995785  0.9691077  0.20000000 0.68571429
MIR6726      26.00000000  1.0000000  0.45325470        NaN
PUSL1         1.06614077  1.0291987  0.48571429 0.68571429
CPSF3L        0.99529979  0.9748618  0.48571429 0.48571429
MIR6727      59.04820237  1.0000000  0.45325470        NaN
⋮            ⋮           ⋮           ⋮          ⋮
BRCC3         1.0462555    0.9811687 0.20000000 0.48571429
VBP1          1.1196700    1.0416826 0.02857143 0.48571429
RAB39B        1.0126810    0.9352217 0.68571429 0.11428571
CLIC2         1.4906162    1.2387152 0.24252556 0.66119671
TMLHE         0.9935351    0.9459884 0.88454944 0.46782508
SPRY3         0.7768119    0.8711076 0.02857143 0.20000000
VAMP7         1.0078526    0.9707596 0.88571429 1.00000000
IL9R          0.9732022    0.9103239 0.88571429 0.34285714
RPS4Y1        0.9418755    1.0282765 0.24538346 0.68571429
ZFY           0.9787856    1.0704648 0.56136321 0.34285714
LINC00278     0.6992694    0.9534828 0.23963905 1.00000000
TBL1Y        84.0482024  348.7473271 0.18587673 0.06891844
PRKY          0.8158611    0.8199634 0.20000000 0.34285714
GYG2P1        1.0000000   26.0000000        NaN 0.45325470
TTTY15        0.9306858    0.9779542 0.56136321 0.68571429
USP9Y         0.9216683    1.1013630 0.38363033 0.88571429
DDX3Y         1.0290628    1.1177820 0.77150341 0.88571429
UTY           0.9165708    0.9979554 0.24538346 0.34285714
TMSB4Y        0.9271301    0.7776088 1.00000000 0.56136321
NLGN4Y        2.0109430    1.8321816 0.18315020 0.45959739
TTTY14        0.5675641    0.5675641 0.64455217 0.64455217
CD24          3.6597094    3.1016100 0.21860374 0.35289670
BCORP1        0.7993925    0.6697091 0.24538346 0.24538346
TXLNGY        0.9085783    0.9487924 0.24538346 0.56136321
KDM5D         0.9254965    1.0716901 0.56136321 1.00000000
TTTY10        0.5038998    0.3817401 0.37185137 0.18315020
EIF1AY        1.1170259    1.2339296 0.48571429 0.48571429
RPS4Y2        1.0555683    1.2716042 1.00000000 0.76595483
no_feature    0.9591259    0.9676523 0.02857143 0.02857143
ambiguous     0.9966226    0.9844713 0.68571429 0.48571429

In [105]:
out_tmp1<-data.frame(Sample_ID='DataSet_03_363',TF="MYC",Gene=rownames(myc_diff_tab),Log2FC=log2(myc_diff_tab$fc),P_value=myc_diff_tab$pvalue)

In [106]:
out_tmp2<-data.frame(Sample_ID='DataSet_03_427',TF="FOXP3",Gene=rownames(foxp3_diff_tab),Log2FC=log2(foxp3_diff_tab$fc),P_value=foxp3_diff_tab$pvalue)

In [ ]:
subset(out_tmp1,Gene=="MYC") # 敲除失败

      Sample_ID      TF  Gene Log2FC      P_value
15484 DataSet_03_363 MYC MYC  -0.08675737 0.25

In [ ]:
subset(foxp3_diff_tab,rownames(foxp3_diff_tab)=="FOXP3") # 敲除失败

      fc1      fc2      1          2
FOXP3 1.187199 1.395346 0.02857143 0.02857143